Repository fragaria/karmen, pull requests merged in 2020-07, with the labels that each got.

#293 Ignore deprecation warning in itsdangerous
  src/karmen_backend/pytest.ini
Labels: fix

#291 Prevent rerendering form while being edited
  src/karmen_frontend/src/components/listings/printers-table.js
Labels: bug

#296 allow zero temperature
  src/karmen_frontend/src/components/tabs/printer/controls-tab.js
Labels: bug

#281 Feat/another ci improvements
  .travis.yml
Labels: enhancement

#295 Stop dispatching loadPrinters when user is logged out
  src/karmen_frontend/src/actions/printers/reading.js
Labels: bug

#297 fixes broken video stream
  base.env
  src/karmen_backend/Pipfile
  src/karmen_backend/Pipfile.lock
  src/karmen_backend/server/__init__.py
  src/karmen_backend/server/routes/printers.py
  src/karmen_backend/server/services/redlock_cache.py
  src/karmen_backend/tests/routes/test_printers.py
Labels: bug

#294 Feat/email validation
  src/karmen_backend/Pipfile
  src/karmen_backend/Pipfile.lock
  src/karmen_backend/server/models/users_me.py
  src/karmen_backend/server/routes/users.py
  src/karmen_backend/server/routes/users_me.py
  src/karmen_backend/server/services/validators.py
  src/karmen_backend/tests/services/test_validators.py
  src/karmen_frontend/src/assets/styles.scss
  src/karmen_frontend/src/components/forms/form-utils.js
  src/karmen_frontend/src/routes/organizations/add-user.js
  src/karmen_frontend/src/routes/unauthorized/register.js
  src/karmen_frontend/src/routes/unauthorized/request-password-reset.js
Labels: enhancement
