Repository fragaria/karmen, pull requests merged in 2020-06, with the labels that each got.

#209 fixed dependabot conditon
  .github/workflows/dependabot-approve.yml
Labels: bug

#195 Feat/test users api
  docker-compose.yml
  src/karmen_backend/Makefile
  src/karmen_backend/docker-compose.test.yml
  src/karmen_backend/openapi/swagger.yaml
  src/karmen_backend/server/__init__.py
  src/karmen_backend/server/models/__init__.py
  src/karmen_backend/server/models/users_me.py
  src/karmen_backend/server/routes/__init__.py
  src/karmen_backend/server/routes/tests_admin.py
  src/karmen_backend/server/routes/users_me.py
  src/karmen_backend/tests/routes/test_tests_admin.py
  src/karmen_backend/tests/utils.py
Labels: enhancement

#189 UX Polishment: Printer Settings: Printer settings form as reusable component
  src/karmen_frontend/cypress/integration/printers/listing_spec.js
  src/karmen_frontend/src/assets/styles.scss
  src/karmen_frontend/src/components/listings/printers-table.js
  src/karmen_frontend/src/components/printers/printer-settings.js
  src/karmen_frontend/src/components/tabs/printer/settings-tab.js
  src/karmen_frontend/src/components/tabs/settings/printers-tab.js
  src/karmen_frontend/src/routes/organizations/organization-settings.js
  src/karmen_frontend/src/routes/printers/printer-detail.js
  src/karmen_frontend/src/routes/printers/printer-settings.js
Labels: enhancement, javascript

#171 Registration: Better textation after register form submit
  src/karmen_frontend/cypress/integration/unauthorized/registration_spec.js
  src/karmen_frontend/src/assets/styles.scss
  src/karmen_frontend/src/routes/unauthorized/register.js
Labels: enhancement, good first issue, javascript

#230 Fixed crash on edge case when user deletes printer after check queue …
  src/karmen_backend/server/tasks/check_printer.py
  src/karmen_backend/tests/tasks/test_check_printer.py
Labels: bug

#231 If user has no organization, app does not crash and let's user create…
  src/karmen_backend/openapi/swagger.yaml
  src/karmen_backend/server/routes/tests_admin.py
  src/karmen_backend/server/services/mailer/templates/registration_verification.py
  src/karmen_backend/tests/routes/test_tests_admin.py
  src/karmen_frontend/cypress/integration/organizations/adding_spec.js
  src/karmen_frontend/cypress/integration/user/no_organization.js
  src/karmen_frontend/cypress/support/commands.js
  src/karmen_frontend/src/app.js
  src/karmen_frontend/src/components/menu.js
  src/karmen_frontend/src/routes/add-organization.js
  src/karmen_frontend/src/routes/app-root.js
  src/karmen_frontend/src/routes/no-organization.js
Labels: bug, enhancement

#256 Modified UWSGI config to ignore client disconnects errors.
  src/karmen_backend/scripts/uwsgi.ini
Labels: bug
